### ISSUE TITLE
Send and receive non JSON

### ISSUE THREAD

**Issue by tucow** [jbloemendal/jquery-simple-websocket#11]
Hey Jannis,

first of all, thanks for this awesome plugin but I have a small suggestion ;) since I like the way the plugin works I don't like how it cannot handle non-JSON messages.

To solve this I changed the `.bind('message', ...)` function:
> 			.bind('message', function(e) {
> 				try {
> 					var json = $.evalJSON(e.originalEvent.data);
> 				} catch(err) {
> 					console.log("Not a JSON string: ", e)
> 					var json = e.originalEvent.data;
> 				}
> 				if (opt[e.type]) {
> 					opt[e.type].call(this, json);
> 				}
> 			}).bind('error', function(e) {
> 				if (opt.error) {
> 					opt.error.call(this, e);
> 				}
> 			});

And also the self-invoking function within `_send: function(data)`:
> 			(function(json) {
> 				self._reConnect.apply(self, []).done(function(ws) {
> 					if (data !== null && data === 'object') {
> 						ws.send(json);
> 					} else {
> 						ws.send(data);
> 					}
> 					attempt.resolve.apply(self, [self._api]);
> 				}).fail(function(e) {
> 					attempt.rejectWith.apply(self, [e]);
> 				});
> 			})(JSON.stringify(data));

Do you see any chance implementing something like that to handle non-JSON stuff?

Bests,
Andreas

**Comment by jbloemendal** [comment]
Hello Andreas,
thanks for your idea, we could add for example a data type configuration property:

8<----
var socket = $.simpleWebSocket({
                                 url: 'ws://127.0.0.1:3000/',
                                 dataType: 'xml' // or 'json'
                               });
8<----

What do you think?

Kind regards,
Jannis

**Comment by tucow** [comment]
Good morning Jannis,
thank's for your fast reply. I also thought about that but I'd rather put the property into the send function and an automatic check into the message binding just in case there's an unexpected response.

For example I was expecting the first response to be JSON but it's plain HTML since it's "needed" somewhere else -.-

So I can always control what I am sending but never be sure what I'm getting.

Bests,
Andreas

**Comment by jbloemendal** [comment]
Good morning,

I understand you want one socket handling multiple types, from my point of view that's not what you want a server to handle. If you define a strict type you define what you send and receive, if there is an exception thrown saying I don't handle html only type xyz, you can than create a new socket for html communication, that way concerns are staying clear.

What's the actual use case you handle, so I understand the idea better?

Kind regards,
Jannis

**Comment by jbloemendal** [comment]
BTW, existing tests still should pass for keeping api compatibility. I'll take a look at the problem when I have time.

**Comment by jbloemendal** [comment]
Hello Andreas,

I just added a test and some code, would this suffice your usecase?
 
```
    it('receives echo xml msg from server', function(done) {
        var simpleXmlWebSocket = $.simpleWebSocket({
            url: 'ws://127.0.0.1:3000/',
            attempts: 60, // default values
            timeout: 10000,
            dataType: 'xml'
        });

        simpleXmlWebSocket.connect().done(function() {
            expect(simpleXmlWebSocket.isConnected()).toBe(true);

            simpleXmlWebSocket.listen(function(xmlDocument) {
                expect(xmlDocument.firstChild.tagName).toBe('msg');
                expect(xmlDocument.firstChild.textContent).toBe('hello');
                done();
            });

            simpleXmlWebSocket.send('<msg>hello</msg>');
        }).fail(function(e) {
            expect(true).toBe(false);
            done();
        });
    });
```

**Comment by jbloemendal** [comment]
See this test:
```
it('sends json and receives xml msg from server.', function(done) {
        var simpleXmlWebSocket = $.simpleWebSocket({
            url: 'ws://127.0.0.1:3000/',
            attempts: 60, // default values
            timeout: 10000,
            dataType: 'json'
        });

        simpleXmlWebSocket.connect().done(function() {
            expect(simpleXmlWebSocket.isConnected()).toBe(true);

            simpleXmlWebSocket.listen(function(data) {
                try {
                    var domParser = new DOMParser();
                    var dom = domParser.parseFromString(data, "text/xml");
                    expect(true).toBe(true);
                } catch (e) {
                    expect(true).toBe(false);
                }
                done();
            });

            simpleXmlWebSocket.send({'cmd': 'xmlResponse', 'text': 'hello'});
        }).fail(function(e) {
            expect(true).toBe(false);
            done();
        });

    });
```

**Comment by jbloemendal** [comment]
I'll tag and release version 0.0.9-SNAPSHOT soon.
