### ISSUE TITLE
Implement protocol level ping/pong

### ISSUE THREAD

**Issue by karolyi** [jbloemendal/jquery-simple-websocket#22]
Hey,

websocket pings are part of the protocol for a [long time](https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_servers#Pings_and_Pongs_The_Heartbeat_of_WebSockets). They are nothing special, just protocol frames with opcode `0x9`.

This implementation lacks it, so everyone has to implement their own, non-protocol-level solution.

Is there a chance you will implement this in the near future?

**Comment by jbloemendal** [comment]
See as well https://www.w3.org/TR/websockets/#ping-and-pong-frames .

**Comment by jbloemendal** [comment]
If there is demand of the feature due to the indication of a few people, I'll consider implementing it.

**Comment by karolyi** [comment]
I had a 2 day long investigation, the result is you'll be unable to implement it.

Here's why: https://github.com/crossbario/autobahn-js/pull/396#issuecomment-433444831

I guess as the current state of affairs shows, everyone has to implement their proprietary client side hearbeat.

**Comment by oberstet** [comment]
You can construct arbitrary WebSocket binary _payload_, but not arbitrary WebSocket frames in JavaScript in the browser run-time context. You can construct arbitrary frames in JS on NodeJS of course - and hence AutobahnJS supports automatic WebSocket client-initiated heartbeating there, but not for browsers.
